### ISSUE TITLE
英文逗号退回过度

### ISSUE THREAD

**Issue by MrXiaoM** [8aka-Team/NitWikit#339]
#281 

举例 [/docs/contribution/writing-specification/numerical-value.md](https://github.com/8aka-Team/NitWikit/blob/f1c9ce1db771f53ca834133354155f46c51ad9bf/docs/contribution/writing-specification/numerical-value.md?plain=1#L20-L24)
> 数值为千位以上，应添加千分号(半角逗号)。
>
> ```text
> XXX 公司的实收资本为 ￥1，258，000 人民币。
> ```

文字说明是半角逗号，实际是中文逗号。

**Comment by postyizhan** [comment]
https://github.com/8aka-Team/NitWikit/commit/fe9345602f44b1ccde7d0a543e9888903600a85b
如果还有其他地方有问题，请告诉我
